### ISSUE TITLE
Object reference not set to an instance of an object when removing nodes

### ISSUE THREAD

**Issue by mathuin** [djungelorm/krpc-toolkit#1]
I really like the concept in theory, but in practice there's something wrong here.

```
(ksp)(master=) jmt@nala:~/git/djungelorm/krpc-toolkit$ python ./kerbal-x.py
Launching
Coasting out of atmosphere
Circularizing
Traceback (most recent call last):
  File "./kerbal-x.py", line 26, in <module>
    vessel.control.remove_nodes()
  File "<string>", line 1, in <lambda>
  File "/home/jmt/.virtualenvs/ksp/local/lib/python2.7/site-packages/krpc/client.py", line 87, in _invoke
    raise RPCError(response.error)
krpc.error.RPCError: Object reference not set to an instance of an object
```

If there's something I can do to help debug the code, please let me know!

**Comment by djungelorm** [comment]
Just ran it myself and it worked fine!

Can you try setting `verboseErrors = True` in `GameSettings/kRPC/PluginData/settings.cfg` and running it again? Then we'll get a full stack trace.

**Comment by mathuin** [comment]
Here you go!

```
(ksp)(master=) jmt@nala:~/git/djungelorm/krpc-toolkit$ python ./kerbal-x.py 
Launching
Coasting out of atmosphere
Circularizing
Traceback (most recent call last):
  File "./kerbal-x.py", line 26, in <module>
    vessel.control.remove_nodes()
  File "<string>", line 1, in <lambda>
  File "/home/jmt/.virtualenvs/ksp/local/lib/python2.7/site-packages/krpc/client.py", line 87, in _invoke
    raise RPCError(response.error)
krpc.error.RPCError: 'SpaceCenter.Control_RemoveNodes' threw an exception. System.NullReferenceException: Object reference not set to an instance of an object   at KRPC.SpaceCenter.Services.Control.RemoveNodes () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
```

There's nothing specific about the Kerbal-X in this script, right?  It looks like a straightforward ascent to 120k orbit as far as I can tell.

**Comment by djungelorm** [comment]
Yeah nothing special about it. Must be a bug in RemoveNodes. And that stack trace doesn't help much :(

**Comment by djungelorm** [comment]
Could you replace your copy of GameData/kRPC/KRPC.SpaceCenter.dll with this one and try the script? https://krpc.s3.amazonaws.com/deploy/bug/removenodes-nre/508.1/GameData/kRPC/KRPC.SpaceCenter.dll

Should tell us where the NRE is coming from.

**Comment by mathuin** [comment]
Thanks for the DLL!  I don't know how to build kRPC on my Linux box so I was at a loss on how to test further.

```
(ksp)(master=) jmt@nala:~/git/djungelorm/krpc-toolkit$ python ./kerbal-x.py 
Launching
Coasting out of atmosphere
Circularizing
Traceback (most recent call last):
  File "./kerbal-x.py", line 26, in <module>
    vessel.control.remove_nodes()
  File "<string>", line 1, in <lambda>
  File "/home/jmt/.virtualenvs/ksp/local/lib/python2.7/site-packages/krpc/client.py", line 87, in _invoke
    raise RPCError(response.error)
krpc.error.RPCError: 'SpaceCenter.Control_RemoveNodes' threw an exception. System.InvalidOperationException: NRE for FlightGlobals.ActiveVessel.patchedConicSolver   at KRPC.SpaceCenter.Services.Control.RemoveNodes () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
```

**Comment by djungelorm** [comment]
Thanks for the stack trace. For some reason the active vessel doesn't have a patchedConicSolver object (which is what's used to administer maneuver nodes). Odd. This is might not be fixable as its the KSP API that's returning null :(

Can you also try running the script with the control.remove_nodes() line commented out? I'm wondering if it will also break when trying to add a maneuver node for the circularization.

Also, what situation is the vessel in when you run the script? There was a similar issue to this with kOS (KSP-KOS/KOS/issues/834) that was caused by trying to use patchedConicSolver in various "invalid" situations.

**Comment by mathuin** [comment]
When I start the script, the vessel is in pre-launch on the pad.

I think I know what might be happening.

I have not yet improved the tracking center.  I think that means I don't have maneuvering node support.  It's possible that that's why we're seeing the NRE in the patchedConicSolver code.

I ran the script with that line commented out before making the issue, and I got the same error on the circularize() code.

What do you think?

**Comment by djungelorm** [comment]
Ah that's probably it! I've only tested kRPC in sandbox mode. I guess the "fix" here is to check if the patchedConicSolver is null and just return a more useful error message.

**Comment by mathuin** [comment]
Oh good.  Now I'm wondering what other functionality gets enabled in career mode over time that might be accessed by kRPC.  There may be other features which start off disabled but are enabled by progression.

Thanks for helping me solve the mystery!

**Comment by djungelorm** [comment]
I'm wondering that too, but I guess we'll just find out as people use the mod in different ways... At least now if we come across more NullReferenceExceptions we have an idea that it might be career mode related.

Also, looks like I broke the RemoveNodes implementation (after the null checks) in that new dll. You should go back to using the original one ;)

**Comment by mathuin** [comment]
I'll do that.  Thank you again for the help!
